# Generated by Django 5.1.6 on 2025-02-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('detail', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('standard', models.CharField(max_length=50)),
                ('profile_pic', models.FileField(upload_to='image/')),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
