# Generated by Django 5.1.6 on 2025-04-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('query', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='scheduled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=20)),
                ('Day', models.CharField(max_length=10)),
                ('Time', models.IntegerField()),
                ('Teacher', models.CharField(max_length=20)),
            ],
        ),
    ]
